server {
    listen 80;

    # Frontend Requests
    location / {
        proxy_pass http://frontend-container:9095;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    
    location /api/ {
        # 'backend-app' aapke Java container ka naam hoga docker-compose mein
        proxy_pass http://127.0.0.1:8085; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
